describe("Primes", function()
    describe("Sieve", function()
        local sieve = require "primes.primes-ffi".sieve
        local s = sieve(100)
        it("Should mark 1 as nonprime", function()
            assert.is_false(s[1])
          end)
        it("Should mark 2 as prime", function()
            assert.is_true(s[2])
          end)
        it("Should mark 3 as prime", function()
            assert.is_true(s[3])
          end)
        it("Should mark 4 as nonprime", function()
            assert.is_false(s[4])
          end)
      end)
  end)
